theme: minima
title: Your awesome Demo site
author: Steven Burrows
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Test pages site used for demo purposes

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  stevenjburrows # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
